\c giga_dev;

INSERT INTO giga_users(name, username, email, password,image_url)
VALUES
('Lennie', 'RedGhost_24','lnursej22480@yahoo.com', 'Bela9214','picture holder'),
('Zoe','zoegamer','zoe12344@yahoo.com','bighead01','picture holder'),
('Solomon','king_sol','Sol330@yahoo.com','kingsul33','picture holder'),
('Koi','koi_gamer','koi412@yahoo.com','duolc100','picture holder'),
('michele','' ,'michele1125@yahoo.com', 'mich11234', 'picture holder');


INSERT INTO games(title, platform, genre, number_of_players, esrd_rating, publisher, developer, release_date, present, digital, image_url, description) 
VALUES
('Sonic Forces', 'playstation 4', ' Platform game, Action-adventure game', 'single player','E 10+', 'Sega', 'Hardlight', 2017-11-07, TRUE, FALSE, 'https://image.api.playstation.com/cdn/UP0177/CUSA05637_00/vfs1Nf9GvyNIGBRqXMB9MGr3WMMmXVkJ.png?w=1024&thumb=false', 'In SONIC FORCES, the evil Dr. Eggman has conquered much of the world with help from a powerful and mysterious new villain named Infinite. Now, you must assist Sonic and build an army to reclaim the world as they fight against chaos and destruction.'),
('Jump Force', 'playstation 4', 'Fighting game, Adventure game', 'Multiplayer and single-player', 'teen adolescents', ' Namco Bandai Games America Inc.', 'Spike Chunsoft', 2019-02-15, TRUE, FALSE, 'https://upload.wikimedia.org/wikipedia/en/0/0c/Jumpforcegame.jpg', 'When the real world collides with many of the Shōnen Jump universes, humanity is invaded by the "Venoms", an army of mind-controlled villains led by Kane and Galena. In order to fight back, many heroes are recruited to join the "Jump Force" under the leadership of Director Glover and his A.I. partner Navigator. But a suspicious figure is using both the Jump Force and the Venoms as an attempt to gain a mysterious artifact and merge all worlds into one.'),
('Little Nightmares Complete Edition', 'PlayStation 4', 'Puzzle, Adventure game, Platform game, Survival horror, adventure', 'single-player', 'teen adolescents', ' Bandai Namco Entertainment ', 'Tarsier Studios', 2017-10-26, TRUE, FALSE, 'https://image.api.playstation.com/vulcan/ap/rnd/202204/1908/pam5dUS6w13ovToXCy8mcRZ6.png', 'Little Nightmares Complete Edition is a 2017 puzzle-platformer game developed by Tarsier Studios and published by Bandai Namco Entertainment. The game follows Six, a young girl who is trapped in the Maw, a dark and twisted world inhabited by monstrous creatures. Players must guide Six through the Maw, solving puzzles and avoiding the creatures in order to escape.'),
('Naruto Shippuden: Ultimate Ninja Storm 4', 'playstation 4', 'Fighting game, Action-adventure game', 'Single-player and multiplayer', 'teen adolescents', 'Bandai Namco Entertainment', 'CyberConnect2', 2016-02-04, TRUE, FALSE, 'https://cdn.dlcompare.com/game_tetiere/upload/gameimage/file/7442.jpeg', ' NARUTO SHIPPUDEN™: Ultimate Ninja® STORM 4, a broad set of Ninja Skills will be yours to use against the fiercest foes you`ll ever encounter. Massive attacks in the form of secret techniques, energetic evolutions with the “Awakening”, the inimitable shurikens & kunais and a unique playstyle for each ninja!'),
('Demon Slayer -Kimetsu no Yaiba- The Hinokami Chronicles', 'PlayStation 4', ' Fighting, action', ' Single-player and multiplayer', 'teen adolescents', 'Sega, Aniplex', ' CyberConnect2', 2021-10-14, TRUE, FALSE , 'https://upload.wikimedia.org/wikipedia/en/4/40/Demon_Slayer_Kimetsu_no_Yaiba_%E2%80%93_The_Hinokami_Chronicles_box_art.jpg', 'Follow the story from Demon Slayer: Kimetsu no Yaiba Tanjiro Kamado, Unwavering Resolve Arc—where Tanjiro joins the Demon Slayer Corps— to Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train featuring the Flame Hashira, Kyojuro Rengoku!Players can choose from a roster of over 20 characters to battle in 3D arenas. The game also features a story mode that follows the events of the anime series.'),
('God of War', 'PlayStation 4', 'Action-Adventure', 'single-player', 'Mature', 'Santa Monica Studio', 'Sony Interactive Entertainment', 2018-04-20, TRUE, FALSE, 'https://upload.wikimedia.org/wikipedia/en/a/a7/God_of_War_4_cover.jpg', 'God of War is a 2018 action-adventure game developed by Santa Monica Studio and published by Sony Interactive Entertainment. The game is the eighth installment in the God of War series, and the sequel to 2010''s God of War III. The game follows Kratos, the former Greek god of war, as he sets out on a journey to the Norse realm of Midgard with his son Atreus.'),
('Super Smash Bros Ultimate', 'Nintendo Switch', 'Fighting', '8', 'Everyone 10+', 'Nintendo', 'Nintendo', 2018-12-07, TRUE, FALSE, 'https://assets.nintendo.com/image/upload/c_fill,w_1200/q_auto:best/f_auto/dpr_2.0/ncom/en_US/games/switch/s/super-smash-bros-ultimate-switch/hero','Super Smash Bros. Ultimate is a 2018 crossover fighting game developed by Sora Ltd. and published by Nintendo. The game is the fifth installment in the Super Smash Bros. series, and features characters from various Nintendo, third-party, and indie franchises. Players can battle each other in 2D arenas, and can also team up in 2v2 matches. A powerful & unknown enemy has attacked - and won. Hundreds of video game characters from past Nintendo games have been turned to spirits by Galeem and his army of Master Hands. Only Kirby has escaped the initial attack, riding a star. Now Kirby must venture by himself and discover the nature of the World of Light, as he attempts to free the other fighters, which have been turned into mindless puppets by Galeem.'),
('The Last of Us Part 1', 'PlayStation 4', 'Action-Adventure', 'single-player', 'Mature', 'Naughty Dog', 'Sony Interactive Entertainment', 2013-06-14, TRUE, FALSE,'https://upload.wikimedia.org/wikipedia/en/d/d5/The_Last_of_Us_Cover_Art.png','The Last of Us is an action-adventure survival horror video game developed by Naughty Dog and published by Sony Computer Entertainment. It was released for the PlayStation 3 worldwide on June 14, 2013. Players control Joel, a smuggler tasked with escorting a teenage girl, Ellie, across a post-apocalyptic United States.'),
('The Legend of Zelda: Breath of the Wild', 'Nintendo Switch', 'Action-Adventure', '1', 'Everyone 10+', 'Nintendo', 'Nintendo', 2017-03-03, TRUE, FALSE,'https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_2.0/c_scale,w_900/ncom/en_US/games/switch/t/the-legend-of-zelda-breath-of-the-wild-switch/hero','The Legend of Zelda: Breath of the Wild is a 2017 action-adventure game developed and published by Nintendo. The game is the sequel to 2011''s The Legend of Zelda: Skyward Sword. The game follows Link, a Hylian knight, as he sets out to save Princess Zelda and Hyrule from the evil Calamity Ganon. Forget everything you know about The Legend of Zelda games. Step into a world of discovery, exploration, and adventure in The Legend of Zelda: Breath of the Wild, a boundary-breaking new game in the acclaimed series. Travel across vast fields, through forests, and to mountain peaks as you discover what has become of the kingdom of Hyrule in this stunning Open-Air Adventure. Now on Nintendo Switch, your journey is freer and more open than ever. Take your system anywhere, and adventure as Link any way you like.'),
('DragonBall 2 XENOVERSE', 'playstation 4', 'Fighting game', '2-4', 'teen adolescents', 'Bandai Namco Entertainment', 'Dimps', 2015-02-24, TRUE, FALSE, 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e8/Dragon_Ball_Xenoverse_2_cover.jpg/220px-Dragon_Ball_Xenoverse_2_cover.jpg', 'DragonBall 2 XENOVERSE is an action RPG set in the DragonBall universe. Players create their own custom character and travel through time to fight against various enemies, including Frieza, Cell, and Majin Buu. The game features a variety of fighting styles, as well as a robust character customization system'),
('Call of DUTY Ghosts', 'playstation 4', 'First-person shooter', '1-12', 'Mature', 'Activision', 'Infinity Ward', 2013-11-05, TRUE, FALSE, 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8a/Call_of_Duty_Ghosts_cover.jpg/220px-Call_of_Duty_Ghosts_cover.jpg', 'Call of Duty Ghosts is a first-person shooter set in the near future. Players take on the role of members of the Ghosts, a special forces team that is tasked with fighting against a terrorist organization. The game features a variety of new gameplay mechanics, including a dynamic weather system and a dog companion that can be used to attack enemies.'),
('UNCHARTED a thief''s END 4', 'playstation 4', 'Action-Adventure', '1-3', 'Mature', 'Sony Computer Entertainment', 'Naughty Dog', 2016-05-10, TRUE, FALSE, 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c5/Uncharted_4_A_Thief_s_End_cover.jpg/220px-Uncharted_4_A_Thief_s_End_cover.jpg', 'UNCHARTED a thief''s END 4 is an action-adventure game that serves as the conclusion to the Uncharted series. Players take on the role of Nathan Drake, a treasure hunter who is searching for the lost city of Shambhala. The game features a variety of new gameplay mechanics, including a grappling hook and a rope swing.'),
('DESTINY the taken king', 'playstation 4', 'First-person shooter', '1-12', 'Teen', 'Activision', 'Bungie', 2015-09-15, TRUE, FALSE, 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c9/Destiny_The_Taken_King_cover.jpg/220px-Destiny_The_Taken_King_cover.jpg', 'Destiny the taken king is an expansion pack for the video game Destiny. The expansion pack introduces a new story campaign, new enemies, and new weapons and armor. The game also introduces a new raid, which is a challenging cooperative activity that can be played with up to six players.'),
('Mortal Kombat X', 'playstation 4', 'Fighting game', '1-2', 'Mature', 'Warner Bros. Interactive Entertainment', 'NetherRealm Studios', 2015-04-14, TRUE, FALSE, 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Mortal_Kombat_X_cover.jpg/220px-Mortal_Kombat_X_cover.jpg', 'Mortal Kombat X is a fighting game that features a roster of over 30 characters, including new characters such as Cassie Cage and Takeda Takahashi. The game features a variety of new gameplay mechanics, including a new "X-Ray" move that allows players to see their opponent''s bones breaking.'),
('Assassin''s Creed ORIGINS','playstation 4','Action-adventure', '1-4', 'M', 'Ubisoft', 'Ubisoft Montreal', 2017-10-27, TRUE, FALSE, 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6e/Assassins_Creed_Origins_cover.jpg/220px-Assassins_Creed_Origins_cover.jpg', 'Assassin''s Creed ORIGINS is a prequel to the Assassin''s Creed series. The game is set in Ancient Egypt and follows the story of Bayek, a Medjay who is tasked with protecting the people of Egypt from the Order of the Ancients. The game features a variety of new gameplay mechanics, including a new combat system and a new exploration system.'),
('Fallout 4','playstation 4','Action role-playing', '1-4', 'M', 'Bethesda Softworks', 'Bethesda Game Studios', 2015-11-10, TRUE, FALSE, 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Fallout_4_cover.jpg/220px-Fallout_4_cover.jpg', 'Fallout 4 is an action role-playing game set in the post-apocalyptic world of Fallout. Players take on the role of a survivor who is tasked with rebuilding the world after a nuclear war set in Boston. The game features a variety of new gameplay mechanics, including a new crafting system and a new settlement system.'),
('WATCH DOGS 2', 'playstation 4','Action-adventure', '1-4', 'M', 'Ubisoft', 'Ubisoft Montreal', 2016-11-15, TRUE, FALSE, 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e8/Watch_Dogs_2_cover.jpg/220px-Watch_Dogs_2_cover.jpg', 'WATCH DOGS 2 is a sequel to the video game WATCH DOGS. The game is set in San Francisco and follows the story of Marcus Holloway, a hacker who is tasked with taking down a corporation that is controlling the city''s infrastructure. The game features a variety of new gameplay mechanics, including a new hacking system and a new driving system.'),
('MINECRAFT','playstation 4 ','Sandbox', '1-4', 'E10+', 'Mojang', 'Mojang Studios', 2014-03-13, TRUE, FALSE, 'https://upload.wikimedia.org/wikipedia/en/thumb/7/73/Minecraft_cover.jpg/220px-Minecraft_cover.jpg', 'A sandbox video game where players can build anything they can imagine.'),
('The Ninjago movie videogame','playstation 4','Action-adventure', '1', 'E', 'Warner Bros. Interactive Entertainment', 'TT Games', 2017-09-22, TRUE, FALSE, 'https://upload.wikimedia.org/wikipedia/en/thumb/1/14/The_Ninjago_Movie_video_game_cover.jpg/220px-The_Ninjago_Movie_video_game_cover.jpg', 'An action-adventure game based on the 2017 film The Lego Ninjago Movie.'),
('Call of Duty Black OPS 3','playstation 4','First-person shooter','1-4','M','Activision','Treyarch',2015-11-06, TRUE, FALSE,'https://dummyimage.com/400x400/6e6c6e/e9e9f5.png&text=No+Image','Call of Duty Black OPS 3 is a first-person shooter video game developed by Treyarch and published by Activision. It is the eleventh installment in the Call of Duty series and the sequel to Call of Duty: Black Ops II. The game was released worldwide on November 6, 2015, for Microsoft Windows, PlayStation 4, and Xbox One. In Call of Duty Black OPS 3, players take control of a customizable character who is part of a black ops unit. The game features a single-player campaign, a multiplayer mode, and a cooperative mode called Zombies. The single-player campaign takes place in the year 2065 and follows a group of black ops soldiers who are tasked with stopping a global terrorist threat. The multiplayer mode features traditional deathmatch and objective-based game modes, as well as a new mode called "Black Ops Ops". The cooperative mode, Zombies, is a survival mode where players must work together to defeat waves of zombies.The game''s multiplayer mode features a new system called "Specialists", which allows players to choose from a variety of characters with unique abilities.'),
('Madden 22','playstation 5','Sports','1-2','E','Electronic Arts','EA Tiburon', 2021-08-20, TRUE, FALSE, 'https://dummyimage.com/400x400/6e6c6e/e9e9f5.png&text=No+Image','Madden 22 is a sports video game developed by EA Tiburon and published by Electronic Arts. It is the 34th installment in the Madden NFL series and the successor to Madden NFL 21. The game was released worldwide on August 20, 2021, for Microsoft Windows, PlayStation 4, PlayStation 5, Xbox One, and Xbox Series X/S. In Madden 22, players take control of a NFL team and compete against other teams in a variety of game modes, including exhibition games, regular season games, and the playoffs. The game also features a new mode called "Face of the Franchise" where players can create their own player and rise through the ranks of the NFL.Madden 22 features a new physics engine that allows for more realistic gameplay. The game also introduces a new mode called "The Yard", which is a 3v3 street football mode.'),
('SPIDER-MAN Miles Morales','playstation 5','Action-adventure','1-2','T','Sony Interactive Entertainment','Insomniac Games', 2020-11-12, TRUE, FALSE,'https://dummyimage.com/400x400/6e6c6e/e9e9f5.png&text=No+Image','SPIDER-MAN Miles Morales is an action-adventure video game developed by Insomniac Games and published by Sony Interactive Entertainment. It was released on November 12, 2020, for PlayStation 4 and PlayStation 5. The game is a standalone expansion to Marvel''s Spider-Man and follows the story of Miles Morales, a new Spider-Man who is struggling to adjust to his new life in Harlem. The game features a new setting, Harlem, which is a vibrant and diverse neighborhood in New York City. Miles Morales also has new abilities, such as the ability to camouflage himself and generate venom blasts.'),
('ASSASSINS CREED VALHALLA','playstation 5','Action-adventure','1-4','M','Ubisoft','Ubisoft Montreal', 2020-11-10, TRUE, FALSE, 'https://dummyimage.com/400x400/6e6c6e/e9e9f5.png&text=No+Image','ASSASSINS CREED VALHALLA is an action-adventure game developed by Ubisoft Montreal and published by Ubisoft. It is the twelfth major installment in the Assassin''s Creed series, and a sequel to Assassin''s Creed Odyssey (2018). The game was released worldwide on November 10, 2020, for Microsoft Windows, PlayStation 4, PlayStation 5, Xbox One, and Xbox Series X/S.'),
('Splatoon 2','NINTENDO SWITCH','Third-person shooter','1-8','E','Nintendo','Nintendo EPD',2017-07-21, TRUE, FALSE, 'https://www.nintendo.com/games/detail/splatoon-2-switch/','Splatoon 2 is a third-person shooter game developed and published by Nintendo. It is the sequel to Splatoon (2015), and was released worldwide on July 21, 2017, for the Nintendo Switch. The game features 4-on-4 turf wars, as well as a variety of other modes, such as ranked battles and salmon run.'),
('MY HERO ONE JUSTICE 2','NINTENDO SWITCH','Fighting','1-2','T','Bandai Namco Entertainment','Byking',2019-03-13, TRUE, FALSE, 'https://dummyimage.com/400x400/6e6c6e/e9e9f5.png&text=No+Image','MY HERO ONE JUSTICE 2 is a fighting game developed by Byking and published by Bandai Namco Entertainment. It is based on the My Hero Academia anime series, and was released worldwide on March 13, 2019, for Microsoft Windows, PlayStation 4, and Nintendo Switch. The game features a roster of over 40 characters, and a variety of different modes, such as story mode, arcade mode, and online multiplayer.'),
('The Lego Movie videogame','NINTENDO SWITCH','Action-adventure','1-4','E','Warner Bros. Interactive Entertainment','TT Games', 2014-02-02 , TRUE, FALSE, 'https://dummyimage.com/400x400/6e6c6e/e9e9f5.png&text=No+Image','The Lego Movie videogame is an action-adventure game developed by TT Games and published by Warner Bros. Interactive Entertainment. It is based on the 2014 film The Lego Movie, and was released worldwide on February 2, 2014, for Microsoft Windows, PlayStation 3, PlayStation 4, Xbox 360, Xbox One, Wii U, and Nintendo 3DS. The game features a variety of different levels, all based on scenes from the film.'),
('Animal Crossing: New Horizons','NINTENDO SWITCH','Simulation','1-4','E','Nintendo','Nintendo EPD', 2020-03-20, TRUE, FALSE,'https://www.nintendo.com/games/detail/animal-crossing-new-horizons-switch/','Animal Crossing: New Horizons is a simulation game developed and published by Nintendo. It is the sixth main installment in the Animal Crossing series, and was released worldwide on March 20, 2020, for the Nintendo Switch. The game allows players to create their own character and move to a deserted island, where they can build a community of animals and decorate their homes.'),
('Animal Crossing: New Horizons','NINTENDO SWITCH','Simulation','1-4','E','Nintendo','Nintendo EPD', 2020-03-20, TRUE, FALSE,'https://www.nintendo.com/games/detail/animal-crossing-new-horizons-switch/','Animal Crossing: New Horizons is a simulation game developed and published by Nintendo. It is the sixth main installment in the Animal Crossing series, and was released worldwide on March 20, 2020, for the Nintendo Switch. The game allows players to create their own character and move to a deserted island, where they can build a community of animals and decorate their homes.'),
('Animal Crossing: New Horizons','NINTENDO SWITCH','Simulation','1-4','E','Nintendo','Nintendo EPD', 2020-03-20 , TRUE, FALSE,'https://www.nintendo.com/games/detail/animal-crossing-new-horizons-switch/','Animal Crossing: New Horizons is a simulation game developed and published by Nintendo. It is the sixth main installment in the Animal Crossing series, and was released worldwide on March 20, 2020, for the Nintendo Switch. The game allows players to create their own character and move to a deserted island, where they can build a community of animals and decorate their homes.'),
('THE LEGEND OF ZELDA: SKYWARD SWORD HD', 'NINTENDO SWITCH', 'Action-adventure', '1-2', 'E10+', 'Nintendo', 'Nintendo EPD', 2019-07-16, TRUE, FALSE, 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c8/The_Legend_of_Zelda_Skyward_Sword_HD_cover.jpg/220px-The_Legend_of_Zelda_Skyward_Sword_HD_cover.jpg', 'THE LEGEND OF ZELDA: SKYWARD SWORD HD is a remaster of the 2002 Nintendo GameCube game THE LEGEND OF ZELDA: SKYWARD SWORD. The game features updated graphics, as well as new features such as the ability to fast-forward through dialogue and the ability to use motion controls to control the sword.'),
('DE BLOB', 'NINTENDO SWITCH', 'Puzzle', '1-2', 'E', 'THQ Nordic', 'de Blob Team', 2017-09-14, TRUE, FALSE, 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0a/DeBlob_cover.jpg/220px-DeBlob_cover.jpg', 'DE BLOB is a puzzle game where players take control of a blob who can change the color of the world around them. The goal of the game is to solve puzzles by changing the color of the environment to match the color of the blob. The game features a variety of levels, as well as a multiplayer mode.'),
('UNDERTALE', 'NINTENDO SWITCH', 'Role-playing', '1', 'E10+', 'Toby Fox', 'Toby Fox', 2018-09-15, TRUE, FALSE, 'https://upload.wikimedia.org/wikipedia/en/thumb/3/34/Undertale_cover.jpg/220px-Undertale_cover.jpg', 'UNDERTALE is a role-playing game where players take control of a human who falls into the Underground, a world inhabited by monsters. The goal of the game is to find a way back to the surface, but players can choose to fight or befriend the monsters they encounter. The game features a variety of endings, depending on the player''s choices.'),
('SUPER MONKEY BALL: BANANA BLITZ HD', 'NINTENDO SWITCH', 'Platform', '1-4', 'E', 'Sega', 'Arzest', 2017-05-24, TRUE, FALSE, 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f1/Super_Monkey_Ball_Banana_Blitz_HD_cover.png/220px-Super_Monkey_Ball_Banana_Blitz_HD_cover.png', 'SUPER MONKEY BALL: BANANA BLITZ HD is a remaster of the 2001 Sega Dreamcast game SUPER MONKEY BALL. The game features updated graphics, as well as new features such as online multiplayer. The game is a platformer where players control a monkey in a ball who must roll through a series of levels to reach the finish line.'),
('HUMAN FALL FLAT ANN EDITION', 'NINTENDO SWITCH', 'Puzzle', '1-4', 'E', 'Curve Digital', 'No Brakes Games', 2018-03-20, TRUE, FALSE, 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c1/Human_Fall_Flat_Anniversary_Edition_cover.jpg/220px-Human_Fall_Flat_Anniversary_Edition_cover.jpg', 'HUMAN FALL FLAT ANN EDITION is a puzzle game where players control a jelly-like character who must solve puzzles by manipulating their body. The game features a variety of levels, as well as a multiplayer mode.');

INSERT INTO systems (user_id, username, system_name, image_url, manufacturer, consoles, controllers, release_date)
VALUES
  (1, 'RedGhost_24', 'PlayStation 5', ARRAY['ps5_front.jpg', 'ps5_back.jpg'], 'Sony', 1, 2, '2020-11-12'),
  (1, 'RedGhost_24', 'PlayStation 4', ARRAY['switch_front.jpg', 'switch_back.jpg'], 'Sony', 1, 1, '2013-11-15'),
  (2, 'zoegamer', 'Nintendo Switch gray', ARRAY['switchgray_front.jpg', 'switchgray_back.jpg'], 'Nintendo', 1, NULL, '2017-03-03'),
  (3, 'king_sol', 'Nintendo Switch yellow', ARRAY['switchyellow_front.jpg', 'switchyellow_side.jpg'], 'Nintendo', 1, NULL, '2017-03-03'),
  (4, 'koi_gamer', 'Nintendo Switch blue', ARRAY['switchblue_front.jpg', 'switchbkue_back.jpg'], 'Nintendo', 1, NULL, '2017-03-03'),
  (4, 'koi_gamer', 'PC Gaming System', ARRAY['pc_front.jpg', 'pc_back.jpg'], 'Custom Microsoft build', 1, NULL, '2021-02-26'),
  (5, 'mom', 'PC Gaming System laptop', ARRAY['3ds_front.jpg', '3ds_back.jpg'], 'Custom Microsoft build', 1, NULL, '2020-02-26'),
  (1, 'RedGhost_24', 'PlayStation 4 pro', ARRAY['switch_front.jpg', 'switch_back.jpg'], 'Sony', 1, 1, '2016-11-10');

